version: '3.9'

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=digit_library_project_db
      - POSTGRES_PASSWORD=root
    image: postgres:latest
    networks:
      - backendLibrary

  app:
    container_name: app
    image: asil88/digitlibrary:v9
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - backendLibrary

networks:
  backendLibrary:
    driver: bridge
